### PR TITLE
composer update

### PR DESCRIPTION
**Pull request by madurapa**

### CODE REVIEW

**Comment by jcergolj** [comment]
Hi, @madurapa thanks for your pull request. Would it be possible to revert .gitignore file permissions to 644, please? 
Furthermore, would you mind remove yarn from the .gitignore file if possible?
And lastly, please add yourself to the list of contributors ;) 

Thanks for all your help much appreciated!

**Comment by madurapa** [comment]
Hi, @jcergolj I have reverted .gitignore permission.
it's just yarn-error.log, do you want me to remove that also?

**Comment by jcergolj** [comment]
Yes, please ;)

BTW, thanks for adding Laravel IDE Helper Generator.

And please add yourself as a contributor.

**Comment by madurapa** [comment]
Done.

**Comment by jcergolj** [comment]
Thanks, @madurapa, for your contribution and patience.

**Pull request merged**
